name: Build and Upload Release

on:
  push:
    branches: ["release-push-test"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y gcc make

    - name: Build
      run: make release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: ./1bit_converter.exe